### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by Nerdyvedi** [Hzzone/AgeFlow#2]
Hi, I wanted to test the model on custom images.
Would you be uploading the test code as well?

**Comment by Hzzone** [comment]
If you mean generation, please refer to https://github.com/Hzzone/AgeFlow/blob/c217d513563699dddc3f9f9fbf93e2d163daca26/flow/models.py#L234. Otherwise, the interpolation should be used. I will update it when I am free.

**Comment by Nerdyvedi** [comment]
@Hzzone I want to be able to translate an input image to target age.
As mentioned in this figure from the paper.
<img width="1034" alt="Screenshot 2021-06-03 at 9 57 05 PM" src="https://user-images.githubusercontent.com/23276664/120679344-b255ee00-c4b6-11eb-8bee-b8a720bdaa1c.png">

**Comment by Hzzone** [comment]
Please refer to the readme.

**Comment by Nerdyvedi** [comment]
@Hzzone Could you please guide me. I am not able to find in the readme how to run the pretrained model?

**Comment by Tony00728** [comment]
@Nerdyvedi  Sorry to bother you, Do you know how to test it ?
