### ISSUE TITLE
Where can I download the SCAF or  LCAF dataset

### ISSUE THREAD

**Issue by bixiwen** [Hzzone/AgeFlow#3]
Hi，in your CVPR paper（When Age-Invariant Face Recognition Meets Face Age Synthesis: A Multi-Task Learning Framework (CVPR 2021 oral)），create and release a new large cross-age face dataset (LCAF). Where can I download the SCAF or  LCAF dataset? Thank you

**Comment by Hzzone** [comment]
https://www.dropbox.com/home/MTLFace

**Comment by bixiwen** [comment]
@Hzzone Thank you very much, but the link cannot open, The file "MTLFace" does not exist.

**Comment by Hzzone** [comment]
Plz use VPN if you are in China.

**Comment by bixiwen** [comment]
![image](https://user-images.githubusercontent.com/23132852/121999367-cfa48980-cddf-11eb-927d-cb29ae489c1e.png)
@Hzzone, I used VPN

**Comment by bixiwen** [comment]
@Hzzone , I used VPN.
![image](https://user-images.githubusercontent.com/23132852/121999626-1f835080-cde0-11eb-89dd-9693b649e1d6.png)

**Comment by Hzzone** [comment]
https://www.dropbox.com/sh/fj848yjz9602nhb/AADgCTUkVOgAv4uRyn5GwdiJa?dl=0

**Comment by Hzzone** [comment]
https://github.com/Hzzone/MTLFace/blob/master/README.md#dataset

**Comment by bixiwen** [comment]
@Hzzone Thank you very much

**Comment by khawar-islam** [comment]
Hi @Hzzone 

I am outside of China and I am unable to access your new dataset 

"Where can I download the SCAF or LCAF dataset? Thank you

Regards,
Khawar

**Comment by Hzzone** [comment]
Please see the README: https://github.com/Hzzone/MTLFace/blob/master/README.md#dataset.
![image](https://user-images.githubusercontent.com/19267349/122912586-0e5fb400-d38b-11eb-9b76-1b41245a2a7a.png)

Google Drive: https://drive.google.com/drive/folders/1YmaBkHoRt85cysQX2TJZmasRwfrchiWO

If you cannot access Google Drive, try Baidu disk https://pan.baidu.com/s/1_9rrxOyicTxzLeoCMmnE5g

**Comment by Hzzone** [comment]
I would like to update the README for better clarification.

**Comment by baiyun442** [comment]
> https://www.dropbox.com/sh/fj848yjz9602nhb/AADgCTUkVOgAv4uRyn5GwdiJa?dl=0

The link is invalid, can you share it again

![Image](https://github.com/user-attachments/assets/795baab4-d4da-47a6-9ff2-9494ffc3ab8d)
