### ISSUE TITLE
Unable to find Testing Dataset

### ISSUE THREAD

**Issue by khawar-islam** [Hzzone/AgeFlow#5]
Dear @Hzzone,

Would it be possible to share the testing datasets of FGNET,  FG-NET (leave-one-out), FG-NET (MF1)?
If you have a .bin file or script that will create a .bin file of images, I will be much appreciated it.

Thank you @Hzzone

**Comment by Hzzone** [comment]
https://yanweifu.github.io/FG_NET_data/
