### ISSUE TITLE
its  a nice work and thanks for you share.

### ISSUE THREAD

**Issue by leefly072** [Hzzone/AgeFlow#6]
I have some questions about the knowledge distilling loss, I read the paper found this parameter is set as 1.4 for MORPH. but I cannot find where is the code of the knowledge distilling loss and how to set it to suitable for different datasets.
Can you give me some advice about it? Thanks again for your help.

**Comment by leefly072** [comment]
![image](https://user-images.githubusercontent.com/18061849/129582085-63005c19-c2d0-431d-9b06-7ec8b1253583.png)
I also found the last two items to look the same. Did I miss some information on the paper?

**Comment by leefly072** [comment]
![image](https://user-images.githubusercontent.com/18061849/129582518-46b4ea06-f6aa-4540-b8d8-6788430a33fd.png)
I also found the last two items to look the same. Did I miss some information on the paper?

**Comment by Hzzone** [comment]
I am sorry for that mistake. It should be z_{t,\alpha_i} - z_{s,\alpha_i} with the form of Eq. 5
The term you discussed should be tuned for different datasets. You can try some example images to visualize the traversing on the latent space.

**Comment by leefly072** [comment]
Thank you for your reply, can you tell the code for the knowledge distilling loss?  I did find the define the knowledge distilling loss in the source code? did you training the model to utilize it or you did not upload it?

**Comment by leefly072** [comment]
Thank you for your reply, can you tell the code for the knowledge distilling loss? I did not find the define the knowledge distilling loss in the source code? did you training the model to utilize it or you did not upload it?

**Comment by Hzzone** [comment]
I have not uploaded it yet. Below is the code:
![image](https://user-images.githubusercontent.com/19267349/129718371-06bf2ade-7cbb-46d5-b644-59ec3fb8a552.png)

**Comment by leefly072** [comment]
Thanks again for your share.

**Comment by ShaohuaL** [comment]
> I have not uploaded it yet. Below is the code: ![image](https://user-images.githubusercontent.com/19267349/129718371-06bf2ade-7cbb-46d5-b644-59ec3fb8a552.png)

could you please uploaded the code of distilling loss? Especially the inner function of self.updater.translate() @Hzzone
